name: Deploy UI to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'ASE.UI/package-lock.json'

      - name: Install Dependencies
        working-directory: ./ASE.UI
        run: npm ci --legacy-peer-deps

      - name: Build
        working-directory: ./ASE.UI
        run: npm run build:github-pages

      - name: Create .nojekyll file
        run: touch ./ASE.UI/dist/ase-client/.nojekyll

      - name: Create 404.html for SPA routing
        run: cp ./ASE.UI/dist/ase-client/index.html ./ASE.UI/dist/ase-client/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './ASE.UI/dist/ase-client'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 