name: Deploy .NET 9 API to Azure

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ASE.API/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Build and publish
      run: |
        cd ASE.API
        dotnet publish -c Release -o ./publish
        
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'data-anomaly-api'
        package: './ASE.API/publish' 